/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as ExercisesIdRouteImport } from './routes/exercises.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExercisesRoute,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExercisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/exercises/': typeof ExercisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/exercises': typeof ExercisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/exercises/': typeof ExercisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/dashboard'
    | '/exercises'
    | '/pricing'
    | '/profile'
    | '/exercises/$id'
    | '/exercises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/profile'
    | '/exercises/$id'
    | '/exercises'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/dashboard'
    | '/exercises'
    | '/pricing'
    | '/profile'
    | '/exercises/$id'
    | '/exercises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExercisesRoute: typeof ExercisesRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
  }
}

interface ExercisesRouteChildren {
  ExercisesIdRoute: typeof ExercisesIdRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesIdRoute: ExercisesIdRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExercisesRoute: ExercisesRouteWithChildren,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
